services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: spellcheck-backend

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    container_name: spellcheck-frontend
    depends_on:
      - backend